---
'./files/sources/deployit-3.9.3-server.zip':
   download_url: "https://tech.xebialabs.com/download/deployit/3.9.3/deployit-3.9.3-server.zip"
   username:
   password:
'./files/sources/deployit-3.9.3-cli.zip':
   download_url: "https://tech.xebialabs.com/download/deployit/3.9.3/deployit-3.9.3-cli.zip"
   username:
   password:
